/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdminSpotifyImport } from './routes/admin/spotify'

// Create Virtual Routes

const UiLazyImport = createFileRoute('/ui')()
const KontoLazyImport = createFileRoute('/konto')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UiLazyRoute = UiLazyImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ui.lazy').then((d) => d.Route))

const KontoLazyRoute = KontoLazyImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/konto.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AdminSpotifyRoute = AdminSpotifyImport.update({
  id: '/admin/spotify',
  path: '/admin/spotify',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoLazyImport
      parentRoute: typeof rootRoute
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiLazyImport
      parentRoute: typeof rootRoute
    }
    '/admin/spotify': {
      id: '/admin/spotify'
      path: '/admin/spotify'
      fullPath: '/admin/spotify'
      preLoaderRoute: typeof AdminSpotifyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/konto': typeof KontoLazyRoute
  '/ui': typeof UiLazyRoute
  '/admin/spotify': typeof AdminSpotifyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/konto': typeof KontoLazyRoute
  '/ui': typeof UiLazyRoute
  '/admin/spotify': typeof AdminSpotifyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/konto': typeof KontoLazyRoute
  '/ui': typeof UiLazyRoute
  '/admin/spotify': typeof AdminSpotifyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/konto' | '/ui' | '/admin/spotify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/konto' | '/ui' | '/admin/spotify'
  id: '__root__' | '/' | '/konto' | '/ui' | '/admin/spotify'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  KontoLazyRoute: typeof KontoLazyRoute
  UiLazyRoute: typeof UiLazyRoute
  AdminSpotifyRoute: typeof AdminSpotifyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  KontoLazyRoute: KontoLazyRoute,
  UiLazyRoute: UiLazyRoute,
  AdminSpotifyRoute: AdminSpotifyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/konto",
        "/ui",
        "/admin/spotify"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/konto": {
      "filePath": "konto.lazy.tsx"
    },
    "/ui": {
      "filePath": "ui.lazy.tsx"
    },
    "/admin/spotify": {
      "filePath": "admin/spotify.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
